services:
  ngdb:
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ngdb_data:/var/lib/postgresql/data

volumes:
  ngdb_data: